-- ============================================================
-- Nabbis Collections — Supabase starter schema (draft)
-- ============================================================
-- Tables referenced by src/lib/database.ts:
--   products, categories, vendors, users, orders
-- Storage bucket referenced by code:
--   "site-images" (see src/lib/database.ts / upload helpers)
--
-- IMPORTANT:
-- This repo does not include migrations/SQL yet.
-- Use this file as a starting point and adjust column names/types
-- to match your app expectations and any existing Supabase project state.
--
-- Run in Supabase SQL Editor:
--   Supabase Dashboard -> SQL Editor -> New query -> paste -> Run
--
-- Notes:
-- - The app uses RLS. Policies are included as placeholders.
-- - Adjust auth logic to your desired roles model.
-- ============================================================

-- ---------- Enums (match src/lib/types.ts) ----------
do $$
begin
  if not exists (select 1 from pg_type where typname = 'vendor_status') then
    create type vendor_status as enum ('active', 'pending', 'suspended');
  end if;

  if not exists (select 1 from pg_type where typname = 'order_status') then
    create type order_status as enum ('pending', 'confirmed', 'shipped', 'delivered', 'cancelled');
  end if;

  if not exists (select 1 from pg_type where typname = 'order_delivery_type') then
    create type order_delivery_type as enum ('nairobi', 'parcel', 'pickup');
  end if;

  if not exists (select 1 from pg_type where typname = 'order_payment_method') then
    create type order_payment_method as enum ('mpesa', 'airtel', 'card');
  end if;

  if not exists (select 1 from pg_type where typname = 'order_payment_status') then
    create type order_payment_status as enum ('pending', 'paid', 'failed');
  end if;

  if not exists (select 1 from pg_type where typname = 'user_role') then
    create type user_role as enum ('customer', 'vendor', 'admin');
  end if;
end $$;

-- ---------- categories ----------
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text unique not null,
  description text not null default '',
  image text not null default '',
  productCount integer not null default 0
);

-- ---------- vendors ----------
create table if not exists public.vendors (
  id bigint generated by default as identity primary key,
  name text not null,
  logo text not null default '',
  description text not null default '',
  rating numeric not null default 0,
  totalProducts integer not null default 0,
  totalSales numeric not null default 0,
  status vendor_status not null default 'pending',
  joinedDate timestamp with time zone not null default now(),
  location text not null default ''
);

-- ---------- users (app-level users table) ----------
-- WARNING: This is app-specific and may differ from Supabase auth.users.
-- Ensure your UI writes to this table, or map auth to app users.
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text unique not null,
  phone text,
  avatar text,
  role user_role not null default 'customer',
  joinedDate timestamp with time zone not null default now()
);

-- ---------- products ----------
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text unique not null,
  price numeric not null,
  oldPrice numeric,
  image text not null default '',
  images jsonb not null default '[]'::jsonb,
  category text not null default '',
  badge text,
  vendor text not null default '',
  vendorId bigint not null references public.vendors(id) on delete cascade,
  rating numeric not null default 0,
  reviews integer not null default 0,
  stock integer not null default 0,
  description text not null default '',
  tags jsonb not null default '[]'::jsonb,
  featured boolean not null default false,
  isFlash boolean not null default false
);

-- ---------- orders ----------
create table if not exists public.orders (
  id text primary key,
  items jsonb not null default '[]'::jsonb,
  total numeric not null default 0,
  status order_status not null default 'pending',
  created_at timestamp with time zone not null default now(),
  deliveryType order_delivery_type not null default 'parcel',
  paymentMethod order_payment_method not null default 'mpesa',
  paymentStatus order_payment_status not null default 'pending'
);

-- ---------- indexes ----------
create index if not exists idx_products_vendorId on public.products (vendorId);
create index if not exists idx_orders_created_at on public.orders (created_at);
create index if not exists idx_categories_slug on public.categories (slug);

-- ---------- RLS (placeholders) ----------
-- Enable RLS for app tables.
alter table public.products enable row level security;
alter table public.categories enable row level security;
alter table public.vendors enable row level security;
alter table public.users enable row level security;
alter table public.orders enable row level security;

-- NOTE: The following policies are intentionally permissive defaults.
-- Tighten them for production (vendor/admin scoping, etc.).

-- categories: allow read
create policy "categories_read_all"
on public.categories for select
using (true);

-- vendors: allow read
create policy "vendors_read_all"
on public.vendors for select
using (true);

-- products: allow read
create policy "products_read_all"
on public.products for select
using (true);

-- orders: allow insert/update only to authenticated users (placeholder)
-- You must adjust to your auth model (e.g., JWT claims).
create policy "orders_read_authenticated"
on public.orders for select
using (auth.role() = 'authenticated');

create policy "orders_insert_authenticated"
on public.orders for insert
with check (auth.role() = 'authenticated');

create policy "orders_update_authenticated"
on public.orders for update
using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');

-- users: allow read/write for authenticated (placeholder)
create policy "users_read_authenticated"
on public.users for select
using (auth.role() = 'authenticated');

create policy "users_write_authenticated"
on public.users for insert
with check (auth.role() = 'authenticated');

create policy "users_update_authenticated"
on public.users for update
using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');

-- vendors: allow update for authenticated vendors (placeholder)
create policy "vendors_update_authenticated"
on public.vendors for update
using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');

-- ---------- Storage bucket note ----------
-- Create a bucket named: site-images
-- Ensure it’s configured according to your security model.
