-- Nabbis Collections - Create users table for app compatibility
-- The app queries 'public.users' but the initial schema created 'profiles'.
-- This migration creates the users table expected by database.ts

CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  phone TEXT,
  avatar TEXT,
  role user_role NOT NULL DEFAULT 'customer',
  joinedDate TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Seed default users
INSERT INTO public.users (name, email, phone, role) VALUES
  ('Admin User', 'admin@nabbis.com', '+254700000000', 'admin'),
  ('Test Customer', 'customer@nabbis.com', '+254711111111', 'customer'),
  ('Test Vendor', 'seller@nabbis.com', '+254722222222', 'vendor')
ON CONFLICT (email) DO NOTHING;

-- Enable RLS
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- Allow public read for authenticated users
CREATE POLICY "Users can read own data"
  ON public.users FOR SELECT
  USING (auth.role() = 'authenticated' OR auth.role() = 'service_role');

CREATE POLICY "Service role can manage all users"
  ON public.users FOR ALL
  USING (auth.role() = 'service_role');

-- Create index
CREATE INDEX IF NOT EXISTS idx_users_email ON public.users(email);
